"use client";

import React, { useState } from "react";
import {
  AlertTriangle,
  XCircle,
  CheckCircle2,
  Filter,
  Wrench,
  Check,
  ShieldCheck,
  Copy,
  Info,
  Clock,
  ArrowRight,
} from "lucide-react";
import { ValidationIssue } from "@/lib/comparison-types";

interface ValidationIssueListProps {
  issues: ValidationIssue[];
  onQuickFixClick: (issue: ValidationIssue) => void;
  onAcknowledgeWarning: (issueId: string) => void;
}

export function ValidationIssueList({
  issues,
  onQuickFixClick,
  onAcknowledgeWarning,
}: ValidationIssueListProps) {
  const [filter, setFilter] = useState<"all" | "blocking" | "warnings" | "resolved">("all");

  const filteredIssues = issues.filter((issue) => {
    if (filter === "blocking") return issue.severity === "blocking_error" && !issue.is_resolved;
    if (filter === "warnings") return issue.severity === "warning" && !issue.is_resolved;
    if (filter === "resolved") return issue.is_resolved;
    return true;
  });

  const getIssueTypeBadge = (type: string) => {
    switch (type) {
      case "mandatory_missing":
        return (
          <span className="text-[10px] font-semibold text-slate-700 bg-slate-100 px-2 py-0.5 rounded">
            Mandatory Field Miss
          </span>
        );
      case "type_range_discrepancy":
        return (
          <span className="text-[10px] font-semibold text-rose-700 bg-rose-50 px-2 py-0.5 rounded border border-rose-100">
            Range / Data Conflict
          </span>
        );
      case "duplicate_detected":
        return (
          <span className="text-[10px] font-semibold text-amber-700 bg-amber-50 px-2 py-0.5 rounded border border-amber-100">
            Duplicate Alert
          </span>
        );
      case "arithmetic_mismatch":
        return (
          <span className="text-[10px] font-semibold text-blue-700 bg-blue-50 px-2 py-0.5 rounded">
            Arithmetic Discrepancy
          </span>
        );
      default:
        return null;
    }
  };

  return (
    <div className="bg-white rounded-xl border border-slate-200 shadow-xs overflow-hidden">
      {/* Header and Filter Tabs */}
      <div className="px-6 py-4 border-b border-slate-200 flex flex-col sm:flex-row sm:items-center justify-between gap-3 bg-white">
        <div>
          <h2 className="text-sm font-bold text-slate-900">
            Granular Data Validation & Hygiene Report
          </h2>
          <p className="text-xs text-slate-500 mt-0.5">
            Real-time checks generated by Validation Engine S2.4 prior to supplier comparison matrix generation.
          </p>
        </div>

        {/* Filter Pills */}
        <div className="flex items-center gap-1.5 bg-slate-100/80 p-1 rounded-lg text-xs font-semibold">
          <button
            onClick={() => setFilter("all")}
            className={`px-2.5 py-1 rounded-md transition-all ${
              filter === "all" ? "bg-white text-slate-900 shadow-xs" : "text-slate-600 hover:text-slate-900"
            }`}
          >
            All ({issues.length})
          </button>
          <button
            onClick={() => setFilter("blocking")}
            className={`px-2.5 py-1 rounded-md transition-all ${
              filter === "blocking" ? "bg-white text-rose-700 shadow-xs" : "text-slate-600 hover:text-rose-700"
            }`}
          >
            Blocking ({issues.filter((i) => i.severity === "blocking_error" && !i.is_resolved).length})
          </button>
          <button
            onClick={() => setFilter("warnings")}
            className={`px-2.5 py-1 rounded-md transition-all ${
              filter === "warnings" ? "bg-white text-amber-700 shadow-xs" : "text-slate-600 hover:text-amber-700"
            }`}
          >
            Warnings ({issues.filter((i) => i.severity === "warning" && !i.is_resolved).length})
          </button>
          <button
            onClick={() => setFilter("resolved")}
            className={`px-2.5 py-1 rounded-md transition-all ${
              filter === "resolved" ? "bg-white text-emerald-700 shadow-xs" : "text-slate-600 hover:text-emerald-700"
            }`}
          >
            Resolved ({issues.filter((i) => i.is_resolved).length})
          </button>
        </div>
      </div>

      {/* Issues List */}
      <div className="divide-y divide-slate-100">
        {filteredIssues.length === 0 ? (
          <div className="py-12 text-center space-y-2">
            <CheckCircle2 className="w-8 h-8 text-emerald-500 mx-auto" />
            <p className="text-xs font-semibold text-slate-800">No issues found in this filter</p>
            <p className="text-[11px] text-slate-500">All evaluated parameters conform to enterprise validation rules.</p>
          </div>
        ) : (
          filteredIssues.map((issue) => {
            const isBlocking = issue.severity === "blocking_error";

            return (
              <div
                key={issue.id}
                className={`p-4 transition-colors ${
                  issue.is_resolved
                    ? "bg-slate-50/40 opacity-70"
                    : isBlocking
                    ? "bg-rose-50/15 hover:bg-rose-50/25"
                    : "bg-amber-50/10 hover:bg-amber-50/20"
                }`}
              >
                <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4">
                  {/* Left info */}
                  <div className="space-y-1.5 flex-1 min-w-0">
                    <div className="flex flex-wrap items-center gap-2">
                      <span className="font-mono text-[11px] font-bold text-slate-500">
                        {issue.id}
                      </span>
                      {getIssueTypeBadge(issue.issue_type)}
                      {issue.is_resolved ? (
                        <span className="inline-flex items-center gap-1 text-[10px] font-semibold text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded border border-emerald-200">
                          <Check className="w-3 h-3 text-emerald-600" />
                          Resolved ({issue.resolution_type})
                        </span>
                      ) : isBlocking ? (
                        <span className="inline-flex items-center gap-1 text-[10px] font-bold text-rose-700 bg-rose-50 px-2 py-0.5 rounded border border-rose-200">
                          <XCircle className="w-3 h-3 text-rose-600" />
                          Blocking Error
                        </span>
                      ) : (
                        <span className="inline-flex items-center gap-1 text-[10px] font-bold text-amber-700 bg-amber-50 px-2 py-0.5 rounded border border-amber-200">
                          <AlertTriangle className="w-3 h-3 text-amber-600" />
                          Non-Blocking Warning
                        </span>
                      )}
                      <span className="text-[11px] text-slate-600 font-semibold">
                        • {issue.supplier_name}
                      </span>
                    </div>

                    <h4 className="text-xs font-bold text-slate-900">
                      {issue.title}
                    </h4>

                    <p className="text-xs text-slate-600 leading-relaxed max-w-3xl">
                      {issue.description}
                    </p>

                    {/* Discrepancy comparison badge */}
                    <div className="flex flex-wrap items-center gap-3 pt-1 text-[11px]">
                      <div className="flex items-center gap-1.5 text-slate-500">
                        <span className="font-medium text-slate-400">Target Field:</span>
                        <code className="text-slate-800 bg-slate-100 px-1.5 py-0.5 rounded font-mono text-[10px]">
                          {issue.field_name}
                        </code>
                      </div>

                      {issue.current_value !== null && issue.current_value !== undefined && (
                        <div className="flex items-center gap-1 text-slate-600">
                          <span className="font-medium text-slate-400">Current:</span>
                          <span className="font-mono font-semibold text-rose-700 bg-rose-50 px-1.5 py-0.5 rounded">
                            {String(issue.current_value)}
                          </span>
                        </div>
                      )}

                      {issue.suggested_value && (
                        <div className="flex items-center gap-1 text-slate-600">
                          <span className="font-medium text-slate-400">Suggested:</span>
                          <span className="font-mono font-semibold text-emerald-700 bg-emerald-50 px-1.5 py-0.5 rounded">
                            {String(issue.suggested_value)}
                          </span>
                        </div>
                      )}

                      {issue.resolution_note && (
                        <div className="text-[11px] text-slate-500 italic">
                          Audit Note: &ldquo;{issue.resolution_note}&rdquo;
                        </div>
                      )}
                    </div>
                  </div>

                  {/* Right Action buttons */}
                  {!issue.is_resolved && (
                    <div className="flex items-center gap-2 shrink-0">
                      {!isBlocking && (
                        <button
                          onClick={() => onAcknowledgeWarning(issue.id)}
                          className="px-3 py-1.5 text-xs font-semibold rounded-lg border border-slate-200 bg-white text-slate-700 hover:bg-slate-50 transition-colors shadow-xs"
                        >
                          Acknowledge
                        </button>
                      )}

                      <button
                        onClick={() => onQuickFixClick(issue)}
                        className={`inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold rounded-lg text-white transition-colors shadow-xs ${
                          isBlocking
                            ? "bg-rose-600 hover:bg-rose-700"
                            : "bg-blue-600 hover:bg-blue-700"
                        }`}
                      >
                        <Wrench className="w-3.5 h-3.5" />
                        <span>{isBlocking ? "Rectify Blocker" : "Quick Fix"}</span>
                      </button>
                    </div>
                  )}
                </div>
              </div>
            );
          })
        )}
      </div>
    </div>
  );
}
